import {TabName, TokenRiskDataType, TokenRiskFactor} from '../types';

export const timeData = [
  {key: '5', value: 'm'},
  {key: '1', value: 'h'},
  {key: '6', value: 'h'},
  {key: '24', value: 'h'},
];

export const chartTimeData = [
  {key: '1', value: 'm'},
  {key: '15', value: 'm'},
  {key: '1', value: 'h'},
  {key: '4', value: 'h'},
  {key: '24', value: 'h'},
];

export const tokenRiskData: TokenRiskDataType[] = [
  {
    name: 'lpBurned',
    nameData: 'LP Burned',
    descriptionData: 'Allows the owner to remove liquidity at any time.',
    description: 'lpBurnedDescription',
    level: 'danger',
    score: 4000,
  },
  {
    name: 'top10Holders',
    nameData: 'Top 10 Holders',
    descriptionData: 'Top 10 holders own more than 38.54% of the total supply.',
    description: 'top10HoldersDescription',
    level: 'danger',
    score: 5000,
  },
  // {
  //   name: 'veryLowLiquidity',
  //   nameData: 'Very Low Liquidity',
  //   descriptionData: 'The total liquidity for this token is very low.',
  //   description: 'veryLowLiquidityDescription',
  //   level: 'danger',
  //   score: 7500,
  // },
  {
    name: 'lowLiquidity',
    nameData: 'Low Liquidity',
    descriptionData: 'The total liquidity for this token is low.',
    description: 'lowLiquidityDescription',
    level: 'warning',
    score: 5000,
  },
  {
    name: 'freezeAuthorityEnabled',
    nameData: 'Freeze Authority Enabled',
    descriptionData:
      'Tokens can be frozen and prevented from trading in the future.',
    description: 'freezeAuthorityEnabledDescription',
    level: 'danger',
    score: 7500,
  },
  {
    name: 'mintAuthorityEnabled',
    nameData: 'Mint Authority Enabled',
    descriptionData: 'More tokens can be minted by the owner at any time.',
    description: 'mintAuthorityEnabledDescription',
    level: 'danger',
    score: 2500,
  },
  // {
  //   name: 'rugged',
  //   nameData: 'Rugged',
  //   descriptionData: 'No liquidity, token is considered unsafe to purchase.',
  //   description: 'ruggedDescription',
  //   level: 'danger',
  //   score: 20000,
  // },
  // {
  //   name: 'noSocialMedia',
  //   nameData: 'No social media',
  //   descriptionData: 'Token has no associated social media links.',
  //   description: 'noSocialMediaDescription',
  //   level: 'warning',
  //   score: 2000,
  // },
  // {
  //   name: 'noFileMetadata',
  //   nameData: 'No file metadata',
  //   descriptionData: 'Token has no file metadata.',
  //   description: 'noFileMetadataDescription',
  //   level: 'warning',
  //   score: 100,
  // },
  // {
  //   name: 'pumpFunContractRisks',
  //   nameData: 'Pump.fun contract risks',
  //   descriptionData:
  //     'Pump.fun contracts can be changed by Pump.fun at any time.',
  //   description: 'pumpFunContractRisksDescription',
  //   level: 'warning',
  //   score: 100,
  // },
  // {
  //   name: 'incompleteBondingCurve',
  //   nameData: 'Incomplete bonding curve',
  //   descriptionData: 'No Raydium liquidity pool, bonding curve not complete.',
  //   description: 'incompleteBondingCurveDescription',
  //   level: 'warning',
  //   score: 4000,
  // },
  // {
  //   name: 'transitioningToRaydium',
  //   nameData: 'Transitioning to Raydium',
  //   descriptionData: 'Token is currently transitioning to Raydium.',
  //   description: 'transitioningToRaydiumDescription',
  //   level: 'warning',
  //   score: 100,
  // },
  // {
  //   name: 'priceDecrease',
  //   nameData: 'Price decrease',
  //   descriptionData: 'Price decreased by more than 50% in the last 24 hours.',
  //   description: 'priceDecreaseDescription',
  //   level: 'warning',
  //   score: 1000,
  // },
];

export const utcOffsets = [
  // {
  //   zone: '(UTC−12)',
  //   label: 'Baker Island',
  //   i18Label: 'bakerIsland',
  //   value: '-12',
  // },
  {
    zone: '(UTC−11)',
    label: 'American Samoa',
    i18Label: 'americanSamoa',
    value: '-11',
  },
  {zone: '(UTC−10)', label: 'Honolulu', i18Label: 'honolulu', value: '-10'},
  {zone: '(UTC−09)', label: 'Anchorage', i18Label: 'anchorage', value: '-9'},
  {zone: '(UTC−08)', label: 'Los Angeles', i18Label: 'losAngeles', value: '-8'},
  {zone: '(UTC−07)', label: 'Denver', i18Label: 'denver', value: '-7'},
  {zone: '(UTC−06)', label: 'Mexico City', i18Label: 'mexicoCity', value: '-6'},
  {zone: '(UTC−05)', label: 'New York', i18Label: 'newYork', value: '-5'},
  {zone: '(UTC−04)', label: 'Santiago', i18Label: 'santiago', value: '-4'},
  {
    zone: '(UTC−03)',
    label: 'Buenos Aires',
    i18Label: 'buenosAires',
    value: '-3',
  },
  {
    zone: '(UTC−02)',
    label: 'South Georgia Island',
    i18Label: 'southGeorgiaIsland',
    value: '-2',
  },
  {zone: '(UTC−01)', label: 'Azores', i18Label: 'azores', value: '-1'},
  {zone: '(UTC±00)', label: 'London', i18Label: 'london', value: '0'},
  {zone: '(UTC+01)', label: 'Berlin', i18Label: 'berlin', value: '+1'},
  {zone: '(UTC+02)', label: 'Athens', i18Label: 'athens', value: '+2'},
  {zone: '(UTC+03)', label: 'Istanbul', i18Label: 'istanbul', value: '+3'},
  {zone: '(UTC+04)', label: 'Dubai', i18Label: 'dubai', value: '+4'},
  {zone: '(UTC+05)', label: 'Karachi', i18Label: 'karachi', value: '+5'},
  {zone: '(UTC+06)', label: 'Almaty', i18Label: 'almaty', value: '+6'},
  {zone: '(UTC+07)', label: 'Bangkok', i18Label: 'bangkok', value: '+7'},
  {zone: '(UTC+08)', label: 'Beijing', i18Label: 'beijing', value: '+8'},
  {zone: '(UTC+09)', label: 'Tokyo', i18Label: 'tokyo', value: '+9'},
  {zone: '(UTC+10)', label: 'Sydney', i18Label: 'sydney', value: '+10'},
  {
    zone: '(UTC+11)',
    label: 'Solomon Islands',
    i18Label: 'solomonIslands',
    value: '+11',
  },
  {zone: '(UTC+12)', label: 'Auckland', i18Label: 'auckland', value: '+12'},
  {zone: '(UTC+13)', label: 'Nukuʻalofa', i18Label: 'nukualofa', value: '+13'},
  {zone: '(UTC+14)', label: 'Kiritimati', i18Label: 'kiritimati', value: '+14'},
];

export const tabNames: TabName[] = [
  'trending',
  'volume',
  'marketCap',
  'new',
  'aboutToGraduate',
  'graduate',
];
