export default {
  loading: 'Loading...',
  widiCode: 'Widi Code',
  getStarted: 'Get Started',
  tradingLeader: 'Trading Leader',
  tradingLeaders: 'Trading Leaders',
  copier: 'Copier',
  copied: 'Copied',
  copiedMessage: 'Text copied to clipboard',
  ok: 'Ok',
  cancel: 'Cancel',
  save: 'Save',
  delete: 'Delete',
  error: 'An error occurred',
  retry: 'Retry',
  success: 'Success',
  confirm: 'Confirm',
  exit: 'Exit',
  active: 'Active',
  passive: 'Passive',
  close: 'Close',
  closed: 'Closed',
  name: 'Name',
  username: 'Username',
  continue: 'Continue',
  readNow: 'Read Now',
  d: '{{value}}d',
  day: '{{value}} Day',
  days: '{{value}} Days',
  trend: 'Trend',
  mostCopied: 'Most Copied',
  favorites: 'Favorites',
  edit: 'Edit {{name}}',
  settings: 'Settings',
  en: 'English',
  tr: 'Turkish',
  'zh-CN': 'Chinese (Simplified)',
  'zh-TW': 'Chinese (Traditional)',
  m: '{{value}}m',
  minutes: '{{value}} Minute',
  h: '{{value}}h',
  hours: '{{value}} Hour',
  y: '{{value}}y',
  years: '{{value}} Year',
  mo: '{{value}}mo',
  months: '{{value}} Month',
  s: '{{value}}s',
  seconds: '{{value}} Second',
  w: '{{value}}w',
  weeks: '{{value}} Week',
  justNow: 'Just now',
  searchToken: 'Search Token',
  search: 'Search',
  marketCap: 'Market Cap',
  volume: 'Volume',
  liquidity: 'Liquidity',
  noDataAvailable: 'No data available',
  filters: 'Filters',
  filterResult: 'Filter Result',
  clearAll: 'Clear All',
  timePeriod: 'Time Period',
  wallet: 'Wallet',
  poolWallet: 'Pool Wallet',
  walletDomainAddress: 'Address / domain username',
  walletAddress: 'Wallet Address',
  yourWalletAddress: 'Your Wallet Address',
  yourWallet: 'Your Wallet',
  balance: 'Balance',
  send: 'Send',
  sending: 'Sending',
  receive: 'Receive',
  exportWallet: 'Export Wallet',
  poweredBy: 'Powered by {{name}}',
  myTradingPortfolio: 'My Trading Portfolio',
  createNewPortfolio: 'Create a New Portfolio',
  copy: 'Copy',
  performance: 'Performance',
  code: 'Code',
  paste: 'Paste',
  available: 'Available',
  info: 'Info',
  public: 'Public',
  private: 'Private',
  portfolioType: 'Portfolio Type',
  amount: 'Amount',
  solscan: 'Solcan',
  bio: 'Bio',
  buy: 'Buy',
  sell: 'Sell',
  youPay: 'You Pay',
  youReceive: 'You Minimum Receive',
  swap: 'Swap',
  swapNow: 'Swap Now',
  supply: 'Supply',
  done: 'Done',
  auto: 'Auto',
  medium: 'Medium',
  high: 'High',
  veryHigh: 'Very High',
  reloading: 'Reloading...',
  pasteFromClipboard: 'Paste From Clipboard',
  passed: 'Passed',
  failed: 'Failed',
  warning: 'Warning',
  risk: 'Risk',
  currentPnl: 'Current P&L',
  price: 'Price',
  from: 'From',
  to: 'To',
  next: 'Next',
  recents: 'Recents',
  choose: 'Choose',
  max: 'Max',
  custom: 'Custom',
  fast: 'Fast',
  econ: 'Econ',
  sendingTo: 'Sending to',
  executing: 'Executing',
  tradeComplete: 'Trade Complete!',
  tradeError: 'Trade Error',
  tryAgain: 'Please try again.',
  restart: 'Restart',
  removeSecretFromDevice:
    'Do you want to delete your secret information such as wallet information stored on your device?',
  date: 'Date',
  status: 'Status',
  network: 'Network',
  confirmed: 'Confirmed',
  pending: 'Pending',
  share: 'Share',
  timeAgo: {
    years: '{{count}} years ago',
    months: '{{count}} months ago',
    days: '{{count}} days ago',
    hours: '{{count}} hours ago',
    minutes: '{{count}} minutes ago',
    seconds: '{{count}} seconds ago',
    justNow: 'Just now',
  },
};
