export default {
  loading: 'Yükleniyor...',
  widiCode: 'Widi Kodu',
  getStarted: 'Başlayalım',
  tradingLeader: 'Ticaret Lideri',
  tradingLeaders: 'Ticaret Liderleri',
  copier: 'Kopyalayıcı',
  copied: 'Kopyalandı',
  copiedMessage: 'Metin panoya kopyalandı',
  ok: 'Tamam',
  cancel: 'İptal',
  save: 'Kaydet',
  delete: 'Sil',
  error: 'Bir hata oluştu',
  retry: 'Tekrar dene',
  success: 'Başarılı',
  confirm: 'Onayla',
  exit: 'Çıkış yap',
  active: 'Aktif',
  passive: 'Pasif',
  close: 'Kapat',
  closed: 'Kapandı',
  name: 'İsim',
  username: 'Kullanıcı adı',
  continue: 'Devam et',
  readNow: 'Şimdi Oku',
  d: '{{value}}g',
  day: '{{value}} Gün',
  days: '{{value}} Gün',
  trend: 'Trend',
  mostCopied: 'En Çok Kopyalanan',
  favorites: 'Favoriler',
  edit: '{{name}} Düzenle',
  settings: 'Ayarlar',
  en: 'İngilizce',
  tr: 'Türkçe',
  'zh-CN': 'Çince (Basitleştirilmiş)',
  'zh-TW': 'Çince (Geleneksel)',
  m: '{{value}}d',
  minutes: '{{value}} Dakika',
  h: '{{value}}s',
  hours: '{{value}} Saat',
  y: '{{value}}y',
  years: '{{value}} Yıl',
  mo: '{{value}}mo',
  months: '{{value}} Ay',
  s: '{{value}}s',
  seconds: '{{value}} Saniye',
  w: '{{value}}w',
  weeks: '{{value}} Hafta',
  justNow: 'Şimdi',
  searchToken: 'Token Ara',
  search: 'Ara',
  marketCap: 'Piyasa Değeri',
  volume: 'Hacim',
  liquidity: 'Likidite',
  noDataAvailable: 'Veri mevcut değil',
  filters: 'Filtreler',
  filterResult: 'Filtre Sonucu',
  clearAll: 'Tümünü Temizle',
  timePeriod: 'Zaman Dilimi',
  wallet: 'Cüzdan',
  poolWallet: 'Havuz Cüzdanı',
  walletDomainAddress: 'Adres / kullanıcı alan adı',
  walletAddress: 'Cüzdan Adresi',
  yourWalletAddress: 'Sizin Cüzdan Adresiniz',
  yourWallet: 'Sizin Cüzdanınız',
  balance: 'Bakiye',
  send: 'Gönder',
  sending: 'Gönderiliyor',
  receive: 'Al',
  exportWallet: 'Cüzdanı Dışa Aktar',
  poweredBy: '{{name}} tarafından desteklenmektedir',
  myTradingPortfolio: 'Ticaret Portföyüm',
  createNewPortfolio: 'Yeni Bir Portföy Oluştur',
  copy: 'Kopyala',
  performance: 'Performans',
  code: 'Kod',
  paste: 'Yapıştır',
  available: 'Mevcut',
  info: 'Bilgi',
  public: 'Herkese Açık',
  private: 'Özel',
  portfolioType: 'Portföy Türü',
  amount: 'Miktar',
  solscan: 'Solcan',
  bio: 'Biyografi',
  buy: 'Satın Al',
  sell: 'Sat',
  youPay: 'Ödeyeceğiniz',
  youReceive: 'Minimum Alacağınız',
  swap: 'Takas',
  swapNow: 'Şimdi Takas Et',
  supply: 'Arz',
  done: 'Tamamlandı',
  auto: 'Oto',
  medium: 'Orta',
  high: 'Yüksek',
  veryHigh: 'Çok Yüksek',
  reloading: 'Yeniden yükleniyor...',
  pasteFromClipboard: "Pano'dan Yapıştır",
  passed: 'Geçti',
  failed: 'Başarısız',
  warning: 'Uyarı',
  risk: 'Risk',
  currentPnl: 'Güncel P&L',
  price: 'Fiyat',
  from: 'Kaynak',
  to: 'Hedef',
  next: 'Sonraki',
  recents: 'Son Kullanımlar',
  choose: 'Seç',
  max: 'Maks',
  custom: 'Özel',
  fast: 'Hızlı',
  econ: 'Ekonomik',
  sendingTo: 'Gönderiliyor',
  executing: 'Yürütülüyor',
  tradeComplete: 'Takas Tamamlandı!',
  tradeError: 'Takas Hatası',
  tryAgain: 'Lütfen tekrar deneyin.',
  restart: 'Yeniden Başlat',
  removeSecretFromDevice:
    'Cihazınızda saklanan cüzdan bilgileri gibi gizli bilgilerinizi silmek istiyor musunuz?',
  date: 'Tarih',
  status: 'Durum',
  network: 'Ağ',
  confirmed: 'Onaylandı',
  pending: 'Beklemede',
  share: 'Paylaş',
  timeAgo: {
    years: '{{count}} yıl önce',
    months: '{{count}} ay önce',
    days: '{{count}} gün önce',
    hours: '{{count}} saat önce',
    minutes: '{{count}} dakika önce',
    seconds: '{{count}} saniye önce',
    justNow: 'Şimdi',
  },
};
