export default {
  loading: '加载中...',
  getStarted: '开始使用',
  tradingLeader: '交易领导者',
  tradingLeaders: '交易领导者',
  copier: '跟单者',
  copied: '已复制',
  copiedMessage: '文本已复制到剪贴板',
  ok: '确定',
  cancel: '取消',
  save: '保存',
  delete: '删除',
  error: '发生错误',
  retry: '重试',
  success: '成功',
  confirm: '确认',
  exit: '退出',
  active: '活跃',
  passive: '被动',
  close: '关闭',
  username: '用户名',
  continue: '继续',
  readNow: '立即阅读',
  d: '{{value}}天',
  day: '{{value}} 天',
  days: '{{value}} 天',
  trend: '趋势',
  mostCopied: '最多跟单',
  favorites: '收藏夹',
  edit: '编辑 {{name}}',
  settings: '设置',
  en: '英语',
  tr: '土耳其语',
  'zh-CN': '中文（简体）',
  'zh-TW': '中文（繁體）',
  m: '{{value}}分钟',
  minutes: '{{value}} 分钟',
  h: '{{value}}小时',
  hours: '{{value}} 小时',
  searchToken: '搜索代币',
  marketCap: '市值',
  volume: '交易量',
  liquidity: '流动性',
  noDataAvailable: '暂无数据',
  filters: '筛选器',
  filterResult: '筛选结果',
  clearAll: '清除全部',
  timePeriod: '时间段',
  walletAddress: '钱包地址',
  yourWalletAddress: '您的钱包地址',
  balance: '余额',
  send: '发送',
  receive: '接收',
  exportWallet: '导出钱包',
  poweredBy: '由 {{name}} 提供支持',
  myTradingPortfolio: '我的交易组合',
  createNewPortfolio: '创建新组合',
  copy: '复制',
  performance: '表现',
  code: '代码',
  paste: '粘贴',
  available: '可用',
  info: '信息',
  public: '公开',
  private: '私有',
  portfolioType: '投资组合类型',
  amount: '金额',
};
