export default {
  loading: '載入中...',
  getStarted: '開始使用',
  tradingLeader: '交易領導者',
  tradingLeaders: '交易領導者',
  copier: '跟單者',
  copied: '已複製',
  copiedMessage: '文本已複製到剪貼板',
  ok: '確定',
  cancel: '取消',
  save: '儲存',
  delete: '刪除',
  error: '發生錯誤',
  retry: '重試',
  success: '成功',
  confirm: '確認',
  exit: '退出',
  active: '活躍',
  passive: '被動',
  close: '關閉',
  username: '使用者名稱',
  continue: '繼續',
  readNow: '立即閱讀',
  d: '{{value}}天',
  day: '{{value}} 天',
  days: '{{value}} 天',
  trend: '趨勢',
  mostCopied: '最多跟單',
  favorites: '收藏夾',
  edit: '編輯 {{name}}',
  settings: '設定',
  en: '英語',
  tr: '土耳其語',
  'zh-CN': '中文（簡體）',
  'zh-TW': '中文（繁體）',
  m: '{{value}}分鐘',
  minutes: '{{value}} 分鐘',
  h: '{{value}}小時',
  hours: '{{value}} 小時',
  searchToken: '搜尋代幣',
  marketCap: '市值',
  volume: '交易量',
  liquidity: '流動性',
  noDataAvailable: '暫無資料',
  filters: '篩選器',
  filterResult: '篩選結果',
  clearAll: '清除全部',
  timePeriod: '時間段',
  walletAddress: '錢包地址',
  yourWalletAddress: '您的錢包地址',
  balance: '餘額',
  send: '發送',
  receive: '接收',
  exportWallet: '匯出錢包',
  poweredBy: '由 {{name}} 提供支援',
  myTradingPortfolio: '我的交易組合',
  createNewPortfolio: '創建新組合',
  copy: '複製',
  performance: '表現',
  code: '代碼',
  paste: '貼上',
  available: '可用',
  info: '資訊',
  public: '公開',
  private: '私有',
  portfolioType: '投資組合類型',
  amount: '金額',
};
