import {StyleSheet} from 'react-native';
import {
  BORDER_COLORS,
  CARD_COLORS,
  COLORS,
  NOTIFICATION,
} from '../../../../constants/colors';
import {
  BORDER_RADIUS,
  BORDER_WIDTH,
  FONT_SIZES,
  LINE_HEIGHTS,
  scaleFont,
  scaleSize,
  SPACING,
} from '../../../../constants/dimensions';
import {FONTS} from '../../../../constants/fonts';

export default StyleSheet.create({
  fontMedium: {
    fontFamily: FONTS.MEDIUM,
  },
  fontNeue: {
    fontFamily: FONTS.NEUE,
  },
  scrollContainer: {
    flex: 1,
    paddingHorizontal: SPACING.MD_LG,
  },
  settingsContainer: {
    borderRadius: scaleSize(15),
    backgroundColor: COLORS.TERTIARY,
    borderWidth: BORDER_WIDTH.DEFAULT,
    borderColor: BORDER_COLORS.DEFAULT,
    paddingVertical: scaleSize(6),
    paddingRight: scaleSize(8),
    paddingLeft: scaleSize(15),
    flexDirection: 'row',
    alignItems: 'center',
    gap: scaleSize(15),
  },
  settingText: {
    fontSize: scaleFont(12),
    lineHeight: scaleFont(15),
    letterSpacing: scaleFont(0.24),
  },
  settingTextDefaultColor: {
    color: COLORS.WHITE,
  },
  settingTextPrimaryColor: {
    color: COLORS.PRIMARY,
  },
  iconContainer: {
    borderRadius: BORDER_RADIUS.LG,
    backgroundColor: CARD_COLORS.BACKGROUND,
    borderWidth: BORDER_WIDTH.DEFAULT,
    borderColor: BORDER_COLORS.DEFAULT,
    alignItems: 'center',
    justifyContent: 'center',
    padding: SPACING.XS,
  },
  swapContainer: {
    gap: scaleSize(3),
    marginTop: scaleSize(14),
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
  },
  cardContainer: {
    paddingTop: scaleSize(17),
    paddingBottom: scaleSize(25),
    paddingLeft: scaleSize(18),
    paddingRight: scaleSize(14),
    backgroundColor: CARD_COLORS.BACKGROUND,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    borderRadius: BORDER_RADIUS.LG,
    borderWidth: BORDER_WIDTH.THIN,
  },
  cardLeftContainer: {},
  cardRightContainer: {},
  titleSolid: {
    color: '#676A6F',
    fontSize: scaleFont(12),
    lineHeight: LINE_HEIGHTS.XXS,
  },
  amountButton: {
    marginTop: scaleSize(12),
    marginBottom: scaleSize(14),
  },
  amountText: {
    fontSize: scaleFont(34),
    lineHeight: scaleFont(43),
    color: COLORS.WHITE,
    letterSpacing: scaleFont(-0.68),
  },
  usdSmallContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  usdSwapButton: {
    padding: scaleSize(4),
  },
  usdText: {
    fontSize: FONT_SIZES.XS,
    lineHeight: scaleFont(17),
    color: COLORS.WHITE,
  },
  tokenContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: scaleSize(7),
    marginTop: SPACING.XXL,
    borderWidth: BORDER_WIDTH.THIN,
    borderColor: BORDER_COLORS.LIGHT,
    padding: scaleSize(5),
    backgroundColor: COLORS.DARK,
    borderRadius: scaleSize(9),
    minWidth: scaleSize(114),
    marginLeft: 'auto',
  },
  imageContainer: {
    borderRadius: scaleSize(6),
    overflow: 'hidden',
  },
  tokenText: {
    fontSize: scaleFont(16),
    lineHeight: LINE_HEIGHTS.MD,
    letterSpacing: scaleFont(-0.32),
    color: COLORS.WHITE,
  },
  solAmountContainer: {
    marginTop: scaleSize(15),
    gap: scaleSize(10),
    flexDirection: 'row',
    alignItems: 'center',
  },
  maxButton: {
    borderRadius: BORDER_RADIUS.LG,
    backgroundColor: CARD_COLORS.BACKGROUND,
    borderWidth: BORDER_WIDTH.THIN,
    borderColor: BORDER_COLORS.LIGHT,
    paddingVertical: scaleSize(6),
    paddingHorizontal: scaleSize(10),
  },
  maxText: {
    fontSize: FONT_SIZES.XXS,
    lineHeight: scaleFont(13),
    letterSpacing: scaleFont(-0.22),
    color: COLORS.WHITE,
  },
  swapButton: {
    backgroundColor: COLORS.PRIMARY,
    width: scaleSize(41),
    height: scaleSize(41),
    borderRadius: scaleSize(20.5),
    position: 'absolute',
    zIndex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bottomContainer: {
    paddingTop: SPACING.MD_LG,
    marginTop: 'auto',
  },
  percentageContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  percentageButton: {
    width: scaleSize(88),
    height: scaleSize(40),
    borderRadius: scaleSize(14),
    borderWidth: BORDER_WIDTH.THIN,
    borderColor: BORDER_COLORS.TERTIARY,
    alignItems: 'center',
    justifyContent: 'center',
  },
  percentageText: {
    fontSize: scaleFont(14),
    lineHeight: scaleFont(17),
    color: COLORS.WHITE,
  },
  infoContainer: {
    marginTop: scaleSize(16),
  },
  infoTextContainer: {
    paddingHorizontal: scaleSize(11),
    paddingTop: SPACING.XS,
    paddingBottom: scaleSize(7),
    borderWidth: BORDER_WIDTH.THIN,
    borderColor: BORDER_COLORS.SECONDARY,
    borderRadius: scaleSize(9),
    gap: scaleSize(5),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginHorizontal: scaleSize(-10),
  },
  infoText: {
    fontSize: scaleFont(10),
    lineHeight: scaleFont(13),
    letterSpacing: scaleFont(-0.2),
    color: '#676A6F',
  },
  infoIconContainer: {
    width: scaleSize(13.33),
    height: scaleSize(13.33),
    backgroundColor: '#676A6F',
    borderRadius: scaleSize(3),
  },
  sendContainer: {
    paddingTop: SPACING.MD,
  },
  shareButton: {
    borderRadius: scaleSize(9),
    backgroundColor: NOTIFICATION.SUCCESS.TEXT,
    paddingVertical: scaleSize(9.5),
    paddingHorizontal: scaleSize(19.5),
  },
  shareText: {
    color: NOTIFICATION.SUCCESS.BACKGROUND,
    fontFamily: FONTS.ULTRABOLD,
    fontSize: FONT_SIZES.XS,
    lineHeight: scaleFont(17),
    letterSpacing: scaleFont(-0.13),
  },
});
