import {StyleSheet} from 'react-native';
import {BORDER_COLORS, CARD_COLORS, COLORS} from '../../../../constants/colors';
import {
  BORDER_RADIUS,
  BORDER_WIDTH,
  FONT_SIZES,
  LINE_HEIGHTS,
  scaleFont,
  scaleSize,
  SPACING,
} from '../../../../constants/dimensions';
import {FONTS} from '../../../../constants/fonts';

export default StyleSheet.create({
  fontMedium: {
    fontFamily: FONTS.MEDIUM,
  },
  fontNeue: {
    fontFamily: FONTS.NEUE,
  },
  scrollContainer: {
    backgroundColor: COLORS.DARK,
    flex: 1,
  },
  container: {
    flex: 1,
    marginTop: scaleSize(4),
    paddingBottom: SPACING.MD,
    // borderWidth: 1,
    // borderColor: 'red',
  },
  settingsContainer: {
    borderRadius: scaleSize(15),
    backgroundColor: COLORS.TERTIARY,
    borderWidth: BORDER_WIDTH.DEFAULT,
    borderColor: BORDER_COLORS.DEFAULT,
    paddingVertical: scaleSize(6),
    paddingRight: scaleSize(8),
    paddingLeft: scaleSize(15),
    flexDirection: 'row',
    alignItems: 'center',
    gap: scaleSize(15),
  },
  settingText: {
    fontFamily: FONTS.MEDIUM,
    fontSize: scaleFont(12),
    lineHeight: scaleFont(15),
    letterSpacing: scaleFont(0.24),
    color: COLORS.WHITE,
  },
  iconContainer: {
    borderRadius: BORDER_RADIUS.LG,
    backgroundColor: CARD_COLORS.BACKGROUND,
    borderWidth: BORDER_WIDTH.DEFAULT,
    borderColor: BORDER_COLORS.DEFAULT,
    alignItems: 'center',
    justifyContent: 'center',
    padding: SPACING.XS,
  },
  swapContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    position: 'relative',
  },
  itemContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.XS,
  },
  imageContainer: {
    position: 'relative',
  },
  imageSize: {
    borderRadius: BORDER_RADIUS.LG,
    width: scaleSize(35),
    height: scaleSize(35),
  },
  image: {
    borderWidth: BORDER_WIDTH.DEFAULT,
    borderColor: COLORS.DARK,
  },
  titleText: {
    fontFamily: FONTS.MEDIUM,
    fontSize: FONT_SIZES.MD,
    lineHeight: scaleFont(21),
    letterSpacing: scaleFont(-0.34),
    color: COLORS.WHITE,
  },
  solanaContainer: {
    backgroundColor: '#252F6A',
    alignItems: 'center',
    justifyContent: 'center',
  },
  swapButtonContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.PRIMARY,
    borderRadius: BORDER_RADIUS.XL,
    borderWidth: BORDER_WIDTH.THICK,
    borderColor: COLORS.DARK,
    width: scaleSize(49),
    height: scaleSize(49),
    position: 'absolute',
  },
  iconRotate: {
    transform: [{rotate: '90deg'}],
  },
  symbolContainer: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: scaleSize(3),
    paddingHorizontal: scaleSize(4),
    borderRadius: scaleSize(16),
    marginTop: scaleSize(27),
    backgroundColor: COLORS.TERTIARY,
    borderWidth: BORDER_WIDTH.DEFAULT,
    borderColor: BORDER_COLORS.DEFAULT,
    marginHorizontal: 'auto',
    position: 'relative',
  },
  symbolItemContainer: {
    width: scaleSize(85),
    height: scaleSize(35),
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: BORDER_RADIUS.XL,
  },
  symbolItemActiveColor: {
    backgroundColor: CARD_COLORS.BACKGROUND,
  },
  usdText: {
    fontFamily: FONTS.MEDIUM,
    fontSize: scaleFont(24),
    lineHeight: LINE_HEIGHTS.XXL,
    letterSpacing: scaleFont(-0.48),
    color: COLORS.PRIMARY,
  },
  amountContainer: {
    marginTop: scaleSize(14),
    backgroundColor: CARD_COLORS.BACKGROUND,
    borderRadius: BORDER_RADIUS.XXL,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: SPACING.MD_LG,
  },
  amountText: {
    fontFamily: FONTS.MEDIUM,
    fontSize: scaleFont(30),
    lineHeight: scaleFont(38),
    letterSpacing: scaleFont(-0.6),
    color: COLORS.WHITE,
  },
  availableContainer: {
    marginTop: scaleSize(13),
    marginHorizontal: 'auto',
  },
  touchPadContainer: {
    gap: SPACING.MD,
    marginTop: scaleSize(44),
  },
  percentageContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  percentageButton: {
    borderRadius: scaleSize(14),
    borderWidth: BORDER_WIDTH.THIN,
    borderColor: BORDER_COLORS.TERTIARY,
    paddingVertical: scaleSize(13),
    alignItems: 'center',
    justifyContent: 'center',
    width: scaleSize(88),
  },
  percentageText: {
    fontSize: scaleFont(14),
    lineHeight: scaleFont(17),
    color: COLORS.WHITE,
  },
  feeButtonsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: SPACING.SM,
    marginHorizontal: 'auto',
  },
  feeButton: {
    paddingVertical: scaleSize(9),
    paddingHorizontal: scaleSize(15),
    borderRadius: scaleSize(9),
    borderWidth: BORDER_WIDTH.THIN,
    borderColor: BORDER_COLORS.TERTIARY,
  },
  feeButtonText: {
    fontSize: scaleFont(10),
    lineHeight: scaleFont(13),
    letterSpacing: scaleFont(-0.2),
    color: '#676A6F',
  },
});
