export default {
  home: 'Home',
  wallet: 'Wallet',
  leader: 'Leaders',
  profile: 'Profile',
  notifications: 'Notifications',
  portfolio: 'Portfolio',
  token: 'Tokens',
  tokenDetails: 'Token Details',
  logout: 'Logout',
  tradingLeader: 'Trading Leader',
  copier: 'Copier',
  loginWithX: 'Log In with X',
  continue: 'Continue',
  copied: 'Copied',
  help: 'Help',
  basePrivacy: 'Privacy',
  language: 'Language',
  terms: 'Terms',
  editProfile: 'Edit Profile',
  copyDetail: 'Copy Detail',
  beALeaderTrader: 'Be a Lead Trader',
  beALeader: 'Be a Leader',
  viewMyLeaderPortfolio: 'View My Leader Portfolio',
  transactionSettings: 'Transaction Settings',
  widiAccessCode: 'Widi Access Code',
  myWidiAccessCode: 'My Widi Access Code',
};
