export default {
  home: 'Ana Sayfa',
  wallet: 'Cüzdan',
  leader: 'Liderler',
  profile: 'Profil',
  notifications: 'Bildirimler',
  portfolio: 'Portföy',
  token: 'Tokenler',
  tokenDetails: 'Token Detayları',
  logout: 'Çıkış Yap',
  tradingLeader: 'Ticaret Lideri',
  copier: 'Kopyalayıcı',
  loginWithX: 'X ile Giriş Yap',
  continue: 'Devam Et',
  copied: 'Kopyalandı',
  help: 'Yardım',
  basePrivacy: 'Gizlilik',
  language: 'Dil',
  terms: 'Şartlar',
  editProfile: 'Profili Düzenle',
  copyDetail: 'Kopyalama Detayı',
  beALeaderTrader: 'Lider Trader Ol',
  beALeader: 'Lider Ol',
  viewMyLeaderPortfolio: 'Lider Portföyümü Görüntüle',
  transactionSettings: 'İşlem Ayarları',
  widiAccessCode: 'Widi Erişim Kodu',
  myWidiAccessCode: 'Benim WIDI Erişim Kodum',
};
