export default {
  home: '首页',
  wallet: '钱包',
  leader: '领导者',
  profile: '个人资料',
  notifications: '通知',
  portfolio: '投资组合',
  token: '代币',
  logout: '退出登录',
  tradingLeader: '交易领导者',
  copier: '跟单者',
  loginWithX: '使用 X 登录',
  continue: '继续',
  copied: '已复制',
  help: '帮助',
  basePrivacy: '隐私',
  language: '语言',
  terms: '条款',
  editProfile: '编辑个人资料',
  copyDetail: '复制详情',
  beALeader: '成为领先交易者',
};