export default {
  home: '首頁',
  wallet: '錢包',
  leader: '領導者',
  profile: '個人資料',
  notifications: '通知',
  portfolio: '投資組合',
  token: '代幣',
  logout: '退出登入',
  tradingLeader: '交易領導者',
  copier: '跟單者',
  loginWithX: '使用 X 登入',
  continue: '繼續',
  copied: '已複製',
  help: '幫助',
  basePrivacy: '隱私',
  language: '語言',
  terms: '條款',
  editProfile: '編輯個人資料',
  copyDetail: '複製詳情',
  beALeader: '成為領先交易者',
};
